# Generated by Django 5.1.2 on 2024-10-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_class_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '', 'verbose_name_plural': 'Sinh viên'},
        ),
    ]
