# Generated by Django 5.1.1 on 2024-11-11 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Present', max_length=10, verbose_name='Trạng thái điểm danh'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student', verbose_name='Sinh viên'),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=100, verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.teacher', verbose_name='Giảng viên đứng lớp'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.class', verbose_name='Danh sách lớp học phần'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fingerprint_data',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dữ liệu vân tay'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã số sinh viên'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.user', verbose_name='Tài khoản sinh viên'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Mã số giảng viên'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.user', verbose_name='Tài khoản giảng viên'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=10, verbose_name='Chức vụ'),
        ),
    ]
