# Generated by Django 5.1.1 on 2024-11-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_alter_attendance_status_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='finScr',
            field=models.FloatField(default=0, verbose_name='Điểm cuối kỳ'),
        ),
        migrations.AddField(
            model_name='student',
            name='midScr',
            field=models.FloatField(default=0, verbose_name='Điểm giữa kì'),
        ),
    ]
