# Generated by Django 5.1.1 on 2024-11-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_student_finscr_student_midscr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='finScr',
            new_name='fnlScr',
        ),
    ]
