# Generated by Django 5.1.1 on 2024-11-11 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_rename_finscr_student_fnlscr'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Ngày bắt đầu'),
        ),
    ]
