# Generated by Django 5.1.1 on 2024-11-11 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_class_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Giờ học'),
        ),
        migrations.AlterField(
            model_name='class',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Ngày bắt đầu'),
        ),
    ]
